# Generated by Django 4.0.6 on 2024-07-30 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_jobtittle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobTittle',
            new_name='JobTitle',
        ),
    ]
