# Generated by Django 4.0.6 on 2024-08-01 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0006_emptstatus_emptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpicaEmployee',
            fields=[
                ('employeeID', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address_city', models.CharField(blank=True, max_length=100, null=True)),
                ('address_state', models.CharField(blank=True, max_length=100, null=True)),
                ('address_street', models.CharField(blank=True, max_length=100, null=True)),
                ('address_zip', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('birthDate', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('badgeNum', models.CharField(blank=True, max_length=30, null=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('gustoID', models.CharField(blank=True, max_length=30, null=True)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('photo', models.ImageField(null=True, upload_to='employee')),
                ('is_admin', models.BooleanField(default=False)),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.department')),
                ('EmpType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.emptype')),
                ('EmptStatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.emptstatus')),
                ('JobTitle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.jobtitle')),
                ('supervisor_name', models.ForeignKey(blank=True, db_column='supervisor_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.opicaemployee')),
                ('user', models.OneToOneField(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
