# Generated by Django 4.0.6 on 2024-08-01 21:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0007_opicaemployee_delete_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpicaEmployee',
            new_name='Employee',
        ),
    ]
