# Generated by Django 4.0.6 on 2024-08-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_employee_idnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
