# Generated by Django 4.0.6 on 2024-08-22 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_client_employee_createdby_employee_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='EmployeeID',
            field=models.ForeignKey(db_column='EmployeeID', default=0, on_delete=django.db.models.deletion.CASCADE, to='catalog.employee'),
            preserve_default=False,
        ),
    ]
