# Generated by Django 4.0.6 on 2024-08-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_client_employeeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='rate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
