# Generated by Django 4.0.6 on 2024-08-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_employee_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('payDate', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'supervisor approved'), (3, 'Closed')])),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approvedBy', models.CharField(blank=True, max_length=60, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('closedBy', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
