# Generated by Django 4.0.6 on 2024-09-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_remove_employee_code_employee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rate_by_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='schedule_by_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
