# Generated by Django 4.0.6 on 2024-09-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_employee_rate_by_hour_employee_schedule_by_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='schedule_by_day',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
