# Generated by Django 4.0.6 on 2024-12-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_employee_schedule_by_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='rate_by_hour',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
