# Generated by Django 4.0.6 on 2025-08-25 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_employee_rate_by_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='periodEmployeeOvertime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_authorized', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=60, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=60, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.period')),
            ],
        ),
    ]
