# Generated by Django 4.0.6 on 2024-08-21 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_client_employee_createdby_employee_created_date_and_more'),
        ('workTimeControl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paidByComission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_number', models.IntegerField(blank=True, null=True)),
                ('payment_method', models.IntegerField(choices=[(1, 'Credit/Debit Card'), (2, 'Cash')], default=1)),
                ('payment_card', models.CharField(blank=True, max_length=60, null=True)),
                ('payment_amount', models.FloatField(blank=True, null=True)),
                ('rate', models.IntegerField()),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=60, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=60, null=True)),
                ('ClientID', models.ForeignKey(db_column='ClientID', on_delete=django.db.models.deletion.CASCADE, to='catalog.client')),
                ('EmployeeID', models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='catalog.employee')),
            ],
        ),
    ]
