# Generated by Django 4.0.6 on 2024-08-27 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_period'),
        ('workTimeControl', '0002_paidbycomission'),
    ]

    operations = [
        migrations.CreateModel(
            name='paidBySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('regular_hours', models.IntegerField(blank=True, null=True)),
                ('vacation_hours', models.IntegerField(blank=True, null=True)),
                ('sick_hours', models.IntegerField(blank=True, null=True)),
                ('other_hours', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'supervisor approved'), (3, 'Closed')])),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=60, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=60, null=True)),
                ('EmployeeID', models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='catalog.employee')),
                ('periodID', models.ForeignKey(db_column='PeriodID', on_delete=django.db.models.deletion.CASCADE, to='catalog.period')),
            ],
        ),
    ]
