# Generated by Django 4.0.6 on 2024-09-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workTimeControl', '0003_paidbysalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidbythehour',
            name='holiday_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paidbythehour',
            name='overtime_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
