# Generated by Django 4.0.6 on 2024-10-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workTimeControl', '0004_paidbythehour_holiday_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidbysalary',
            name='holiday_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
