# Generated by Django 4.0.6 on 2024-10-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workTimeControl', '0005_paidbysalary_holiday_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidbythehour',
            name='other_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paidbythehour',
            name='sick_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paidbythehour',
            name='vacation_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
