# Generated by Django 4.0.6 on 2024-10-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workTimeControl', '0006_paidbythehour_other_hours_paidbythehour_sick_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidbysalary',
            name='holiday_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paidbysalary',
            name='other_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paidbysalary',
            name='regular_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paidbysalary',
            name='sick_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paidbysalary',
            name='vacation_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
