# Generated by Django 4.0.6 on 2024-12-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_employee_rate_by_hour'),
        ('workTimeControl', '0008_alter_paidbythehour_other_hours_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paidbysalary',
            unique_together={('date', 'EmployeeID')},
        ),
    ]
