# Generated by Django 4.0.6 on 2025-02-13 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_employee_rate_by_hour'),
        ('workTimeControl', '0009_alter_paidbysalary_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='paidByHourManually',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('total_hours', models.FloatField(blank=True, null=True)),
                ('regular_hours', models.FloatField(blank=True, null=True)),
                ('overtime_hours', models.FloatField(blank=True, null=True)),
                ('double_time', models.FloatField(blank=True, null=True)),
                ('vacation_hours', models.FloatField(blank=True, null=True)),
                ('sick_hours', models.FloatField(blank=True, null=True)),
                ('holiday_hours', models.FloatField(blank=True, null=True)),
                ('other_hours', models.FloatField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=600, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'supervisor approved'), (3, 'Closed')])),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=60, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=60, null=True)),
                ('EmployeeID', models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='catalog.employee')),
                ('periodID', models.ForeignKey(db_column='PeriodID', on_delete=django.db.models.deletion.CASCADE, to='catalog.period')),
            ],
            options={
                'unique_together': {('date', 'EmployeeID')},
            },
        ),
    ]
